import json

from agents.conversation_agent import parse_user_query
from agents.ocean_api_agent import fetch_live_conditions
from agents.web_research_agent import research_web
from agents.fusion_agent import fuse
from agents.final_agent import generate_final


def run_orca(user_query: str):
    print("\n[LEVEL 1] Conversational AI...\n")
    intent = parse_user_query(user_query)
    print(json.dumps(intent.model_dump(), indent=2))

    print("\n[LEVEL 2] Live data acquisition...\n")
    location, conditions, live_sources, buoy = fetch_live_conditions(intent)
    print(json.dumps({
        "location": location.model_dump(),
        "conditions": conditions.model_dump(),
        "live_sources": live_sources,
        "nearest_buoy": buoy,
    }, indent=2))

    print("\n[LEVEL 3] Independent web / official-source research...\n")
    web_research = research_web(location)
    print(json.dumps(web_research.model_dump(), indent=2))

    print("\n[LEVEL 4] Validation + fusion + provenance...\n")
    unified = fuse(intent, location, conditions, web_research, live_sources)
    print(json.dumps(unified.model_dump(), indent=2))

    print("\n[LEVEL 5] Gemini ocean intelligence...\n")
    language = generate_final(unified)

    # Measurements and sources are taken from deterministic Level 4 output,
    # not regenerated by Gemini.
    final = {
        "location": unified.location.model_dump(),
        "status": language.status,
        "summary": language.summary,
        "current_conditions": unified.conditions.model_dump(),
        "risks": unified.assessment.model_dump(),
        "data_quality": unified.quality.model_dump(),
        "observations": language.observations,
        "recommendations": language.recommendations,
        "sources": unified.sources + [
            {
                "name": s.source,
                "url": s.url,
                "type": s.source_type,
                "relevance": s.relevance,
            }
            for s in web_research.sources
        ],
    }

    print(json.dumps(final, indent=2, ensure_ascii=False))
    return final


if __name__ == "__main__":
    query = input("\nAsk ORCA: ").strip()
    if not query:
        raise SystemExit("Please enter a question.")
    run_orca(query)
